import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { Quicksand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ['latin'],
  variable: "--font-poppins",
});

const quicksand = Quicksand({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${quicksand.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
